var roman = require('./index.js');

console.log(roman.toInt("I"))
console.log(roman.toInt("II"))
console.log(roman.toInt("III"))
console.log(roman.toInt("IV"))
console.log(roman.toInt("V"))
console.log(roman.toInt("VI"))
console.log(roman.toInt("VII"))
console.log(roman.toInt("VIII"))
console.log(roman.toInt("IX"))
console.log(roman.toInt("X"))
console.log(roman.toInt("XI"))
console.log(roman.toInt("CMXXIV"))

console.log(roman.toRoman(1))
console.log(roman.toRoman(2))
console.log(roman.toRoman(3))
console.log(roman.toRoman(4))
console.log(roman.toRoman(5))
console.log(roman.toRoman(6))
console.log(roman.toRoman(7))
console.log(roman.toRoman(8))
console.log(roman.toRoman(9))
console.log(roman.toRoman(10))
console.log(roman.toRoman(11))
console.log(roman.toRoman(924))
